name: Trigger E2E Action
description: Trigger E2E workflow for a specific version

inputs:
  version:
    description: 'Version'
    required: true
  sha:
    description: 'Commit SHA'
    required: true
  bot_app_id:
    description: 'Bot App Id'
    required: true
  bot_app_key:
    description: 'Bot App Key'
    required: true

runs:
  using: "composite"
  steps:
    - id: create_bot_token
      name: Create bot token
      uses: actions/create-github-app-token@v2
      with:
        app-id: ${{ inputs.bot_app_id }}
        private-key: ${{ inputs.bot_app_key }}
        owner: ${{ github.repository_owner }}
        repositories: |
          frontegg-ios-swift
          e2e-system-tests

    - name: "Trigger E2E tests"
      uses: actions/github-script@v5
      env:
        version: ${{ inputs.version }}
        sha: ${{ inputs.sha }}
      with:
        github-token: ${{ steps.create_bot_token.outputs.token }}
        script: |
          const {sha, version} = process.env;
          const repo = 'frontegg-ios-swift'
          const owner = 'frontegg'
          const e2eRepo = 'e2e-system-tests'
          const workflow_id = 'start-ios-sdk-e2e.yaml'
          const dispatch_id = `${repo}/${sha}`
          
          github.rest.actions.createWorkflowDispatch({
            owner,
            repo: e2eRepo,
            workflow_id,
            ref: 'master',
            inputs: {
              client_framework: 'native-ios',
              version,
              dispatch_id,
            }
          })
