//
//  ApiHelperTests.swift
//  FronteggSwiftTests
//

import XCTest
@testable import FronteggSwift

final class ApiHelperTests: XCTestCase {
    
    var api: Api!
    
    override func setUp() {
        super.setUp()
        api = Api(baseUrl: "https://test.frontegg.com", clientId: "test-client-id", applicationId: nil)
    }
    
    override func tearDown() {
        api = nil
        super.tearDown()
    }
    
    // MARK: - Cookie Name Generation Tests
    
    func test_cookieName_removesFirstDash() {
        // The cookie name is generated by removing the first dash from clientId
        // and prepending "fe_refresh_"
        // For "test-client-id", first dash removed: "testclient-id"
        // Cookie name: "fe_refresh_testclient-id"
        
        // We can't directly access the private cookieName, but we can verify
        // the behavior through getCookieValueFromHeaders
        let setCookie = "fe_refresh_testclientid=some-token; Path=/; HttpOnly"
        
        // Create a mock response - the api should look for the right cookie name
        let url = URL(string: "https://test.frontegg.com/oauth/token")!
        let response = HTTPURLResponse(url: url, statusCode: 200, httpVersion: nil, headerFields: [
            "Set-Cookie": setCookie
        ])!
        
        let cookies = api.getCookiesFromHeaders(response: response)
        // Note: getCookiesFromHeaders looks for fe_refresh_ pattern
        XCTAssertNotNil(cookies)
    }
    
    // MARK: - getCookieValueFromHeaders Tests
    
    func test_getCookieValueFromHeaders_extractsRefreshToken() {
        let setCookie = "fe_refresh_abc123=eyJhbGciOiJIUzI1NiJ9.payload.signature; Path=/; HttpOnly; Secure"
        
        let value = api.getCookieValueFromHeaders(setCookieHeader: setCookie, cookieName: "fe_refresh")
        
        XCTAssertNotNil(value)
        XCTAssertTrue(value!.starts(with: "fe_refresh_"))
        XCTAssertTrue(value!.contains("eyJhbGciOiJIUzI1NiJ9"))
    }
    
    func test_getCookieValueFromHeaders_extractsDeviceToken() {
        let setCookie = "fe_device_xyz789=device-token-value; Path=/; HttpOnly"
        
        let value = api.getCookieValueFromHeaders(setCookieHeader: setCookie, cookieName: "fe_device")
        
        XCTAssertNotNil(value)
        XCTAssertTrue(value!.starts(with: "fe_device_"))
    }
    
    func test_getCookieValueFromHeaders_returnsNil_whenCookieNotFound() {
        let setCookie = "other_cookie=value; Path=/"
        
        let value = api.getCookieValueFromHeaders(setCookieHeader: setCookie, cookieName: "fe_refresh")
        
        XCTAssertNil(value)
    }
    
    func test_getCookieValueFromHeaders_handlesEmptyHeader() {
        let value = api.getCookieValueFromHeaders(setCookieHeader: "", cookieName: "fe_refresh")
        XCTAssertNil(value)
    }
    
    func test_getCookieValueFromHeaders_handlesMultipleCookies() {
        let setCookie = "fe_refresh_abc=token1; Path=/; HttpOnly, fe_device_xyz=device; Path=/"
        
        let refreshValue = api.getCookieValueFromHeaders(setCookieHeader: setCookie, cookieName: "fe_refresh")
        let deviceValue = api.getCookieValueFromHeaders(setCookieHeader: setCookie, cookieName: "fe_device")
        
        XCTAssertNotNil(refreshValue)
        XCTAssertNotNil(deviceValue)
    }
    
    func test_getCookieValueFromHeaders_stopsAtSemicolon() {
        let setCookie = "fe_refresh_client=token-value-here; Path=/; HttpOnly; Secure; SameSite=Strict"
        
        let value = api.getCookieValueFromHeaders(setCookieHeader: setCookie, cookieName: "fe_refresh")
        
        XCTAssertNotNil(value)
        XCTAssertFalse(value!.contains(";"))
        XCTAssertFalse(value!.contains("Path"))
    }
    
    // MARK: - getCookiesFromHeaders Tests
    
    func test_getCookiesFromHeaders_extractsBothCookies() {
        let url = URL(string: "https://test.frontegg.com/oauth/token")!
        let response = HTTPURLResponse(url: url, statusCode: 200, httpVersion: nil, headerFields: [
            "Set-Cookie": "fe_refresh_client=refresh-token; Path=/, fe_device_client=device-token; Path=/"
        ])!
        
        let cookies = api.getCookiesFromHeaders(response: response)
        
        XCTAssertNotNil(cookies)
        XCTAssertNotNil(cookies?.0) // refresh cookie
        XCTAssertNotNil(cookies?.1) // device cookie
    }
    
    func test_getCookiesFromHeaders_handlesOnlyRefreshCookie() {
        let url = URL(string: "https://test.frontegg.com/oauth/token")!
        let response = HTTPURLResponse(url: url, statusCode: 200, httpVersion: nil, headerFields: [
            "Set-Cookie": "fe_refresh_client=refresh-token; Path=/"
        ])!
        
        let cookies = api.getCookiesFromHeaders(response: response)
        
        XCTAssertNotNil(cookies)
        XCTAssertNotNil(cookies?.0) // refresh cookie
        XCTAssertNil(cookies?.1) // device cookie
    }
    
    func test_getCookiesFromHeaders_handlesNoSetCookieHeader() {
        let url = URL(string: "https://test.frontegg.com/oauth/token")!
        let response = HTTPURLResponse(url: url, statusCode: 200, httpVersion: nil, headerFields: [:])!
        
        let cookies = api.getCookiesFromHeaders(response: response)
        
        XCTAssertNotNil(cookies)
        XCTAssertNil(cookies?.0)
        XCTAssertNil(cookies?.1)
    }
    
    // MARK: - HTTPURLResponse Extension Tests
    
    func test_httpURLResponse_isSuccess_returnsTrue_for200() {
        let url = URL(string: "https://example.com")!
        let response = HTTPURLResponse(url: url, statusCode: 200, httpVersion: nil, headerFields: nil)!
        
        XCTAssertTrue(response.isSuccess)
    }
    
    func test_httpURLResponse_isSuccess_returnsTrue_for201() {
        let url = URL(string: "https://example.com")!
        let response = HTTPURLResponse(url: url, statusCode: 201, httpVersion: nil, headerFields: nil)!
        
        XCTAssertTrue(response.isSuccess)
    }
    
    func test_httpURLResponse_isSuccess_returnsTrue_for204() {
        let url = URL(string: "https://example.com")!
        let response = HTTPURLResponse(url: url, statusCode: 204, httpVersion: nil, headerFields: nil)!
        
        XCTAssertTrue(response.isSuccess)
    }
    
    func test_httpURLResponse_isSuccess_returnsTrue_for299() {
        let url = URL(string: "https://example.com")!
        let response = HTTPURLResponse(url: url, statusCode: 299, httpVersion: nil, headerFields: nil)!
        
        XCTAssertTrue(response.isSuccess)
    }
    
    func test_httpURLResponse_isSuccess_returnsFalse_for300() {
        let url = URL(string: "https://example.com")!
        let response = HTTPURLResponse(url: url, statusCode: 300, httpVersion: nil, headerFields: nil)!
        
        XCTAssertFalse(response.isSuccess)
    }
    
    func test_httpURLResponse_isSuccess_returnsFalse_for400() {
        let url = URL(string: "https://example.com")!
        let response = HTTPURLResponse(url: url, statusCode: 400, httpVersion: nil, headerFields: nil)!
        
        XCTAssertFalse(response.isSuccess)
    }
    
    func test_httpURLResponse_isSuccess_returnsFalse_for401() {
        let url = URL(string: "https://example.com")!
        let response = HTTPURLResponse(url: url, statusCode: 401, httpVersion: nil, headerFields: nil)!
        
        XCTAssertFalse(response.isSuccess)
    }
    
    func test_httpURLResponse_isSuccess_returnsFalse_for404() {
        let url = URL(string: "https://example.com")!
        let response = HTTPURLResponse(url: url, statusCode: 404, httpVersion: nil, headerFields: nil)!
        
        XCTAssertFalse(response.isSuccess)
    }
    
    func test_httpURLResponse_isSuccess_returnsFalse_for500() {
        let url = URL(string: "https://example.com")!
        let response = HTTPURLResponse(url: url, statusCode: 500, httpVersion: nil, headerFields: nil)!
        
        XCTAssertFalse(response.isSuccess)
    }
    
    func test_httpURLResponse_isSuccess_returnsFalse_for199() {
        let url = URL(string: "https://example.com")!
        let response = HTTPURLResponse(url: url, statusCode: 199, httpVersion: nil, headerFields: nil)!
        
        XCTAssertFalse(response.isSuccess)
    }
    
    // MARK: - ApiError Tests
    
    func test_apiError_invalidUrl_containsUrlString() {
        let error = ApiError.invalidUrl("https://invalid url with spaces")
        
        if case .invalidUrl(let urlString) = error {
            XCTAssertEqual(urlString, "https://invalid url with spaces")
        } else {
            XCTFail("Expected invalidUrl error")
        }
    }
    
    // MARK: - Api Initialization Tests
    
    func test_api_initializesWithBaseUrl() {
        let customApi = Api(baseUrl: "https://custom.frontegg.com", clientId: "my-client", applicationId: nil)
        XCTAssertNotNil(customApi)
    }
    
    func test_api_initializesWithApplicationId() {
        let customApi = Api(baseUrl: "https://custom.frontegg.com", clientId: "my-client", applicationId: "my-app-id")
        XCTAssertNotNil(customApi)
    }
    
    // MARK: - DEFAULT_TIMEOUT Tests
    
    func test_defaultTimeout_is10Seconds() {
        XCTAssertEqual(Api.DEFAULT_TIMEOUT, 10)
    }
}
